# Site settings
title: Project Pages
description: "An Integrated Scientific Blogging Template"
url: "https://projectpages.github.io"




# Secondary Parameters
baseurl: "/"
header-img: img/home-bg.jpg
headercolor: "#FFFFFF"
logo: img/logos/Project-Pages-New-Logo-Inverted.png


# Jekyll Settings


# Prose Settings
